export type OAuthResponse = {
	sub?: string;
	id?: string;
	email: string;
	email_verified?: boolean;
	default_email?: string;
	emails?: string[];
	name: string;
	given_name?: string;
	family_name?: string;
	first_name?: string;
	last_name?: string;
	login?: string;
	picture?: string;
	default_avatar_id?: string;
	birthday?: string;
	display_name?: string;
	sex?: 'male' | 'female' | null;
	default_phone?: { id: number; number: string };
	access_token?: string;
	refresh_token?: string;
};
